### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by netixen** [vizstra/ui#1]
I wanted to check it out and hack on it but I'm running into req issues.
Shader shader/vert error:
0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES

I Have a Radeon card and use mesa 10.2.8

What do I need?

**Comment by sesteel** [comment]
Right on, sorry about the delayed response... been heads down on another problem.  It looks like NanoVG is looking for an OpenGL3 library.  If you are still interested, you need to checkout vizstra/vg and compile with NANOVG_GL2_IMPLEMENTATION defined locally.
